from functools import wraps
from typing import Any, Callable, Hashable, Iterable

import jax
import jax._src.ad_checkpoint
import jax.core
import jax.extend
import jax.numpy as jnp
from jax import ShapeDtypeStruct
from jax._src import source_info_util
from jax.core import ShapedArray
from jax.extend.core import ClosedJaxpr, Jaxpr, JaxprEqn, Literal, Var

from lox.logdict import logdict
from lox.primitive import lox_p
from lox.stripping import strip_jaxpr
from lox.utils import flatten, is_hashable, select_logs

AxisName = Hashable


def spool(
    fun: Callable,
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
    interval: int | None = None,
    reduce: str | None = None,
    prefix: str = "",
    unify: bool = False,
) -> Callable:
    """
    Spools a function to extract logs generated during its execution.
    Logs are generated by every call to ``lox.log`` within the function.
    Note that spooling also has to obey the underlying laws of JAX.
    Hence all shapes and lengths of the logs must be inferrable during compile time.
    As a direct consequence, loops with non-static lengths (e.g. while loops) are not supported.
    Another implication of this is that spooling an already jitted function that contains
    logging operations will trigger recompilation.

    Args:
        fun (Callable): The function to be spooled.
        argnames (Iterable[str] | None): An optional list of argument names to be spooled.
        tags (Iterable[str] | None): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
        interval (int | None): An optional interval to subsample the logs.
        reduce (str | None): An optional reduction method to apply to the logs.
        prefix (str): An optional prefix to add to the log keys.
        unify (bool): If True, fill missing keys in divergent cond branches with NaN/0/False
            instead of raising an error.

    Returns:
        Callable: A wrapped function that returns the spooled jaxpr and logs.
    """

    @wraps(fun)
    def wrapped(*args, **kwargs):
        args_flat, structure = jax.tree.flatten((args, kwargs))
        static_argnums = tuple(i for i, arg in enumerate(args_flat) if is_hashable(arg))
        closed_jaxpr, out_spooled_shape = make_spooled_jaxpr(
            flatten(fun, structure),
            static_argnums=static_argnums,
            argnames=argnames,
            tags=tags,
            keep_logs=keep_logs,
            unify=unify,
        )(*args_flat)
        dynamic_args_flat = tuple(arg for arg in args_flat if not is_hashable(arg))
        out_spooled_structure = jax.tree.structure(out_spooled_shape)
        out_spooled_flat = jax.core.eval_jaxpr(
            closed_jaxpr.jaxpr, closed_jaxpr.literals, *dynamic_args_flat
        )
        out, logs = jax.tree_util.tree_unflatten(
            out_spooled_structure, out_spooled_flat
        )
        if interval is not None:
            logs = logs.slice[::interval]
        if reduce is not None:
            logs = logs.reduce(reduce)
        if prefix:
            logs = logs.prefix(prefix)
        return out, logs

    return wrapped


def make_spooled_jaxpr(
    fun: Callable,
    static_argnums: int | Iterable[int] = (),
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
    unify: bool = False,
) -> Callable[..., tuple[ClosedJaxpr, Any]]:
    """
    Creates a spooled jaxpr for the given function, extracting logs and their shapes.

    Args:
        fun (Callable): The function to create a jaxpr for.
        static_argnums (int | Iterable[int]): The indices of static arguments.
        argnames (Optional[Iterable[str]]): An optional list of argument names to be spooled.
        tags (Optional[Iterable[str]]): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
        unify (bool): Whether to unify divergent cond branch logs.
    Returns:
        Callable[..., ClosedJaxpr | tuple[ClosedJaxpr, Any]]: A wrapped function that returns the jaxpr and logs.
    """

    def make_jaxpr_f(*args, **kwargs):
        closed_jaxpr, out_shape = jax.make_jaxpr(
            fun,
            static_argnums=static_argnums,
            return_shape=True,
        )(*args, **kwargs)
        new_jaxpr, logs = spool_jaxpr(closed_jaxpr.jaxpr, argnames=argnames, tags=tags, unify=unify)
        closed_jaxpr = ClosedJaxpr(new_jaxpr, closed_jaxpr.consts)
        logs_shape = jax.tree_util.tree_map(
            lambda v: ShapeDtypeStruct(v.aval.shape, v.aval.dtype), logs
        )
        if not keep_logs:
            stripped = strip_jaxpr(closed_jaxpr.jaxpr, argnames=argnames, tags=tags)
            closed_jaxpr = ClosedJaxpr(stripped, closed_jaxpr.consts)
        return closed_jaxpr, (out_shape, logs_shape)

    make_jaxpr_f.__module__ = "jax"
    if hasattr(fun, "__qualname__"):
        make_jaxpr_f.__qualname__ = f"make_jaxpr({fun.__qualname__})"
    if hasattr(fun, "__name__"):
        make_jaxpr_f.__name__ = f"make_jaxpr({fun.__name__})"
    return make_jaxpr_f


def _apply(f: Callable, ctx, *invars: Any) -> tuple[JaxprEqn, Any]:
    """Creates a call_p equation that applies f to invars."""
    invars_avals = jax.tree.map(lambda invar: invar.aval, invars)
    closed_jaxpr_f, shape_f = jax.make_jaxpr(f, return_shape=True)(*invars_avals)
    structure_f = jax.tree.structure(shape_f)
    jaxpr_f = closed_jaxpr_f.jaxpr
    const_literals = [Literal(c, jax.core.get_aval(c)) for c in closed_jaxpr_f.consts]
    call_jaxpr = jaxpr_f.replace(
        constvars=[],
        invars=[*jaxpr_f.constvars, *jaxpr_f.invars],
    )
    eqn_f = JaxprEqn(
        [*const_literals, *jax.tree.leaves(invars)],
        call_jaxpr.outvars,
        jax.extend.core.primitives.call_p,
        {"call_jaxpr": call_jaxpr},
        (),
        source_info_util.current(),
        ctx,
    )
    outvars = jax.tree.unflatten(structure_f, call_jaxpr.outvars)
    return eqn_f, outvars


def _make_fill_eqn(aval: ShapedArray, ctx) -> tuple[JaxprEqn, Var]:
    """Creates a call_p equation with no dynamic invars that produces a constant fill value."""
    if jnp.issubdtype(aval.dtype, jnp.floating):
        fill_val = float("nan")
    elif jnp.issubdtype(aval.dtype, jnp.integer):
        fill_val = 0
    else:
        fill_val = False
    eqn, out_var = _apply(lambda: jnp.full(aval.shape, fill_val, dtype=aval.dtype), ctx)
    return eqn, out_var


def spool_jaxpr(
    jaxpr: Jaxpr,
    argnames: Iterable[str] | None,
    tags: Iterable[str] | None,
    unify: bool = False,
) -> tuple[Jaxpr, logdict]:
    """
    Spools the logs from a jaxpr, extracting logs and their shapes from each equation.
    Returns a new Jaxpr with log outputs appended (does not mutate the input).

    Args:
        jaxpr (Jaxpr): The jaxpr to spool.
        argnames (Iterable[str] | None): An optional list of argument names to be spooled.
        tags (Iterable[str] | None): An optional list of tags to filter the logs.
        unify (bool): Whether to unify divergent cond branch logs.
    Returns:
        tuple[Jaxpr, logdict]: The new jaxpr with log outputs and the logs.
    """
    ctx = jaxpr.eqns[0].ctx if jaxpr.eqns else None

    def spool_lox_p(eqn: JaxprEqn) -> logdict:
        logs_eqn = jax.tree.unflatten(eqn.params["structure"], eqn.invars)
        return select_logs(logs_eqn, eqn.params["tags"], argnames, tags)

    def spool_scan_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        inner_closed = eqn.params["jaxpr"]
        new_inner_jaxpr, logs_jaxpr = spool_jaxpr(inner_closed.jaxpr, argnames, tags, unify)

        if not logs_jaxpr:
            return eqn, logdict({}), []

        logs_jaxpr_avals = jax.tree_util.tree_map(lambda l: l.aval, logs_jaxpr)
        logs_scan_avals = jax.tree_util.tree_map(
            lambda aval: ShapedArray((eqn.params["length"],) + aval.shape, aval.dtype),
            logs_jaxpr_avals,
        )
        logs_scan = jax.tree.map(lambda aval: Var(aval=aval), logs_scan_avals)

        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree.leaves(logs_scan)],
            params={**eqn.params, "jaxpr": ClosedJaxpr(new_inner_jaxpr, inner_closed.consts)},
        )

        def unstack(logs_scan):
            return jax.tree.map(
                lambda l: l.reshape((-1,) + l.shape[2:]),
                logs_scan,
            )

        unstack_eqn, logs_eqn = _apply(unstack, ctx, logs_scan)
        return new_eqn, logs_eqn, [unstack_eqn]

    def spool_cond_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        branches = eqn.params["branches"]
        new_branches = []
        logs_branches = []
        for branch in branches:
            new_branch_jaxpr, logs_branch = spool_jaxpr(branch.jaxpr, argnames, tags, unify)
            new_branches.append(ClosedJaxpr(new_branch_jaxpr, branch.consts))
            logs_branches.append(logs_branch)

        if not any(logs_branches):
            return eqn, logdict({}), []

        all_keys = sorted(set().union(*[set(lb.keys()) for lb in logs_branches]))

        # Shape/dtype mismatches always raise, even with unify=True
        for key in all_keys:
            avals = [lb[key].aval for lb in logs_branches if key in lb]
            if len(set(a.shape for a in avals)) > 1 or len(set(a.dtype for a in avals)) > 1:
                raise ValueError(
                    f"Log key '{key}' has mismatched shapes or dtypes across cond branches."
                )

        # Divergent keys raise unless unify=True
        branch_key_sets = [set(lb.keys()) for lb in logs_branches]
        if any(ks != branch_key_sets[0] for ks in branch_key_sets) and not unify:
            raise ValueError(
                f"cond branches log different keys: {branch_key_sets}. "
                "Use spool(..., unify=True) to fill missing keys with NaN/0/False."
            )

        # Rebuild each branch with log outvars in sorted key order,
        # injecting fill equations for any missing keys.
        unified_branches = []
        for branch, logs_branch in zip(new_branches, logs_branches):
            extra_eqns = []
            ordered_vars = []
            for key in all_keys:
                if key in logs_branch:
                    ordered_vars.append(logs_branch[key])
                else:
                    ref_aval = next(lb[key].aval for lb in logs_branches if key in lb)
                    fill_eqn, fill_var = _make_fill_eqn(ref_aval, ctx)
                    extra_eqns.append(fill_eqn)
                    ordered_vars.append(fill_var)
            n_log_leaves = len(jax.tree.leaves(logs_branch))
            func_outvars = (
                branch.jaxpr.outvars[:-n_log_leaves] if n_log_leaves
                else list(branch.jaxpr.outvars)
            )
            new_branch_jaxpr = branch.jaxpr.replace(
                eqns=branch.jaxpr.eqns + extra_eqns,
                outvars=[*func_outvars, *ordered_vars],
            )
            unified_branches.append(ClosedJaxpr(new_branch_jaxpr, branch.consts))

        logs_eqn = logdict({
            key: Var(aval=ShapedArray(
                next(lb[key].aval for lb in logs_branches if key in lb).shape,
                next(lb[key].aval for lb in logs_branches if key in lb).dtype,
            ))
            for key in all_keys
        })
        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree.leaves(logs_eqn)],
            params={**eqn.params, "branches": tuple(unified_branches)},
        )
        return new_eqn, logs_eqn, []

    def spool_while_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        _, logs_cond = spool_jaxpr(eqn.params["cond_jaxpr"].jaxpr, argnames, tags, unify)
        _, logs_body = spool_jaxpr(eqn.params["body_jaxpr"].jaxpr, argnames, tags, unify)
        if logs_cond or logs_body:
            print(
                "Warning: Spooling for while loops is not supported due to non-static length."
            )
        return eqn, logdict({}), []

    def spool_jit_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        inner_closed = eqn.params["jaxpr"]
        new_inner_jaxpr, logs_jaxpr = spool_jaxpr(inner_closed.jaxpr, argnames, tags, unify)
        if logs_jaxpr:
            logs_eqn = jax.tree.map(
                lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_jaxpr
            )
            const_literals = [Literal(c, jax.core.get_aval(c)) for c in inner_closed.consts]
            call_jaxpr = new_inner_jaxpr.replace(
                constvars=[],
                invars=[*new_inner_jaxpr.constvars, *new_inner_jaxpr.invars],
            )
            new_eqn = eqn.replace(
                primitive=jax.extend.core.primitives.call_p,
                invars=[*const_literals, *eqn.invars],
                outvars=[*eqn.outvars, *jax.tree.leaves(logs_eqn)],
                params={"call_jaxpr": call_jaxpr},
            )
            return new_eqn, logs_eqn, []
        else:
            return eqn, logdict({}), []

    def spool_call_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        new_call_jaxpr, logs_call_jaxpr = spool_jaxpr(eqn.params["call_jaxpr"], argnames, tags, unify)
        if not logs_call_jaxpr:
            return eqn, logdict({}), []

        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_call_jaxpr
        )
        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree_util.tree_leaves(logs_eqn)],
            params={**eqn.params, "call_jaxpr": new_call_jaxpr},
        )
        return new_eqn, logs_eqn, []

    def spool_remat_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        new_remat_jaxpr, logs_remat_jaxpr = spool_jaxpr(eqn.params["jaxpr"], argnames, tags, unify)
        if not logs_remat_jaxpr:
            return eqn, logdict({}), []

        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)),
            logs_remat_jaxpr,
        )
        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree_util.tree_leaves(logs_eqn)],
            params={**eqn.params, "jaxpr": new_remat_jaxpr},
        )
        return new_eqn, logs_eqn, []

    new_eqns = []
    extra_eqns = []
    logs_eqns = []

    for eqn in jaxpr.eqns:
        new_eqn = eqn
        logs_eqn = None
        extra = []

        if eqn.primitive == lox_p:
            logs_eqn = spool_lox_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.scan_p:
            new_eqn, logs_eqn, extra = spool_scan_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.cond_p:
            new_eqn, logs_eqn, extra = spool_cond_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.while_p:
            new_eqn, logs_eqn, extra = spool_while_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.jit_p:
            new_eqn, logs_eqn, extra = spool_jit_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.call_p:
            new_eqn, logs_eqn, extra = spool_call_p(eqn)
        elif eqn.primitive == jax._src.ad_checkpoint.remat_p:
            new_eqn, logs_eqn, extra = spool_remat_p(eqn)

        new_eqns.append(new_eqn)
        extra_eqns.extend(extra)
        if logs_eqn:
            logs_eqns.append(logs_eqn)

    new_outvars = list(jaxpr.outvars)
    if logs_eqns:

        def combine(logs_eqns):
            logs_jaxpr = logs_eqns[0]
            for logs_eqn in logs_eqns[1:]:
                logs_jaxpr += logs_eqn
            return logs_jaxpr

        combine_eqn, logs_jaxpr = _apply(combine, ctx, logs_eqns)
        extra_eqns.append(combine_eqn)
        new_outvars.extend(jax.tree_util.tree_leaves(logs_jaxpr))
    else:
        logs_jaxpr = logdict({})

    new_jaxpr = jaxpr.replace(outvars=new_outvars, eqns=new_eqns + extra_eqns)
    return new_jaxpr, logs_jaxpr
