from functools import wraps
from typing import Any, Callable, Hashable, Iterable

import jax
import jax._src.ad_checkpoint
import jax.core
import jax.extend
from jax import ShapeDtypeStruct
from jax._src import source_info_util
from jax.core import ShapedArray
from jax.extend.core import ClosedJaxpr, Jaxpr, JaxprEqn, Var

from lox.logdict import logdict
from lox.primitive import lox_p
from lox.stripping import strip_jaxpr
from lox.utils import flatten, is_hashable

AxisName = Hashable


def spool(
    fun: Callable,
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
    interval: int | None = None,
    reduce: str | None = None,
    prefix: str = "",
) -> Callable:
    """
    Spools a function to extract logs generated during its execution.
    Logs are generated by every call to ``lox.log`` within the function.
    Note that spooling also has to obey the underlying laws of JAX.
    Hence all shapes and lengths of the logs must be inferrable during compile time.
    As a direct consequence, loops with non-static lengths (e.g. while loops) are not supported.
    Another implication of this is that spooling an already jitted function that contains
    logging operations will trigger recompilation.

    Args:
        fun (Callable): The function to be spooled.
        argnames (Iterable[str] | None): An optional list of argument names to be spooled.
        tags (Iterable[str] | None): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
        interval (int | None): An optional interval to subsample the logs.
        reduce (str | None): An optional reduction method to apply to the logs.
        prefix (str): An optional prefix to add to the log keys.

    Returns:
        Callable: A wrapped function that returns the spooled jaxpr and logs.

    Example:
        Here is an example of how to use ``spool`` to extract logs from a function.

        >>> def f(x):
        >>>     lox.log({"x": x})
        >>>     return x + 1.0
        >>> spool(f)(1.0)
        (2.0, {'x': 1.0})

        Spooling works with arbitrarily nested functions and higher order primitives such as
        ``jax.lax.scan`` or ``jax.lax.cond``.
        The following example shows how to use spooling with a scan operation over the
        previously defined function ``f``.

        >>> def g(xs):
        >>>     carry, ys = jax.lax.scan(lambda c, x: (f(c), x), xs)
        >>>     lox.log({"carry": carry})
        >>> return ys
        >>> spool(g)(jnp.arange(3))
        (Array([2., 3., 4.]), {'carry': 3., 'x': Array([0., 1., 2.])})

        When logging inside of ``jax.lax.cond`` all branches must have the same log structure.
        In this case, both branches return a logdict containing only the key :string:`x`.

        >>> def h(x):
        >>>     return jax.lax.cond(x > 0, lambda x: f(x), lambda x: f(x + 1), x)
        >>> x = 3.0
        >>> spool(h)(x)
        (4.0, {'x': 3.0})

        The optional argument `keep_logs` can be set to `True` to keep the logs in the jaxpr.
        By default, spooling a function twice

        >>> def j(x):
        >>>     y, logs = spool(f)(x)
        >>>     return y
        >>> spool(j)(1.0)
        2.0

    """

    @wraps(fun)
    def wrapped(*args, **kwargs):
        args_flat, structure = jax.tree.flatten((args, kwargs))
        static_argnums = tuple(i for i, arg in enumerate(args_flat) if is_hashable(arg))
        closed_jaxpr, out_spooled_shape = make_spooled_jaxpr(
            flatten(fun, structure),
            static_argnums=static_argnums,
            argnames=argnames,
            tags=tags,
            keep_logs=keep_logs,
        )(*args_flat)
        dynamic_args_flat = tuple(arg for arg in args_flat if not is_hashable(arg))
        out_spooled_structure = jax.tree.structure(out_spooled_shape)
        out_spooled_flat = jax.core.eval_jaxpr(
            closed_jaxpr.jaxpr, closed_jaxpr.literals, *dynamic_args_flat
        )
        out, logs = jax.tree_util.tree_unflatten(
            out_spooled_structure, out_spooled_flat
        )
        if interval is not None:
            logs = logs.slice[::interval]
        if reduce is not None:
            logs = logs.reduce(reduce)
        if prefix:
            logs = logs.prefix(prefix)
        return out, logs

    return wrapped


def make_spooled_jaxpr(
    fun: Callable,
    static_argnums: int | Iterable[int] = (),
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
) -> Callable[..., tuple[ClosedJaxpr, Any]]:
    """
    Creates a spooled jaxpr for the given function, extracting logs and their shapes.

    Args:
        fun (Callable): The function to create a jaxpr for.
        static_argnums (int | Iterable[int]): The indices of static arguments.
        argnames (Optional[Iterable[str]]): An optional list of argument names to be spooled.
        tags (Optional[Iterable[str]]): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
    Returns:
        Callable[..., ClosedJaxpr | tuple[ClosedJaxpr, Any]]: A wrapped function that returns the jaxpr and logs.
    """

    def make_jaxpr_f(*args, **kwargs):
        closed_jaxpr, out_shape = jax.make_jaxpr(
            fun,
            static_argnums=static_argnums,
            return_shape=True,
        )(*args, **kwargs)
        logs = spool_jaxpr(closed_jaxpr.jaxpr, argnames=argnames, tags=tags)
        logs_shape = jax.tree_util.tree_map(
            lambda v: ShapeDtypeStruct(v.aval.shape, v.aval.dtype), logs
        )
        if not keep_logs:
            strip_jaxpr(closed_jaxpr.jaxpr, argnames=argnames, tags=tags)
        return closed_jaxpr, (out_shape, logs_shape)

    make_jaxpr_f.__module__ = "jax"
    if hasattr(fun, "__qualname__"):
        make_jaxpr_f.__qualname__ = f"make_jaxpr({fun.__qualname__})"
    if hasattr(fun, "__name__"):
        make_jaxpr_f.__name__ = f"make_jaxpr({fun.__name__})"
    return make_jaxpr_f


def apply(f: Callable, jaxpr: Jaxpr, *invars: Any) -> Any:
    """
    Applies a function to the invars within the context of the jaxpr.

    Args:
        f (Callable): The function to apply.
        jaxpr (Jaxpr): The jaxpr context in which to apply the function.
        *invars: The input variables to the function.
    Returns:
        Any: The output variables after applying the function.
    """
    invars_avals = jax.tree.map(lambda invar: invar.aval, invars)
    closed_jaxpr_f, shape_f = jax.make_jaxpr(f, return_shape=True)(*invars_avals)
    structure_f = jax.tree.structure(shape_f)
    jaxpr_f = closed_jaxpr_f.jaxpr
    eqn_f = JaxprEqn(
        jax.tree.leaves(invars),
        jaxpr_f.outvars,
        jax.extend.core.primitives.call_p,
        {"call_jaxpr": jaxpr_f},
        (),
        source_info_util.current(),
        jaxpr.eqns[0].ctx,
    )
    jaxpr.eqns.append(eqn_f)
    outvars = jax.tree.unflatten(structure_f, jaxpr_f.outvars)
    return outvars


def spool_jaxpr(
    jaxpr: Jaxpr, argnames: Iterable[str] | None, tags: Iterable[str] | None
) -> logdict:
    """
    Spools the logs from a jaxpr, extracting logs and their shapes from each equation.
    Combines logs from nested equations in the order they will be executed.

    Args:
        jaxpr (Jaxpr): The jaxpr to spool.
    Returns:
        tuple[dict[str, Any], dict[str, Any]]: The logs and their shapes.
    """

    def spool_lox_p(eqn: JaxprEqn) -> logdict:
        logs_eqn = jax.tree.unflatten(eqn.params["structure"], eqn.invars)
        if argnames:
            if tags is None or not any(tag in tags for tag in eqn.params["tags"]):
                logs_eqn = logs_eqn.filter(lambda k, _: k in argnames)
        elif tags:
            if not any(tag in tags for tag in eqn.params["tags"]):
                logs_eqn = logdict({})
        return logs_eqn

    def spool_scan_p(eqn: JaxprEqn) -> logdict:
        logs_jaxpr = spool_jaxpr(eqn.params["jaxpr"].jaxpr, argnames, tags)
        logs_jaxpr_avals = jax.tree_util.tree_map(lambda l: l.aval, logs_jaxpr)
        logs_scan_avals = jax.tree_util.tree_map(
            lambda aval: ShapedArray((eqn.params["length"],) + aval.shape, aval.dtype),
            logs_jaxpr_avals,
        )
        logs_scan = jax.tree.map(lambda aval: Var(aval=aval), logs_scan_avals)
        eqn.outvars.extend(jax.tree.leaves(logs_scan))

        def unstack(logs_scan):
            return jax.tree.map(
                lambda l: l.reshape((-1,) + l.shape[2:]),
                logs_scan,
            )

        logs_eqn = apply(unstack, jaxpr, logs_scan)
        return logs_eqn

    def spool_cond_p(eqn: JaxprEqn) -> logdict:
        branches = eqn.params["branches"]
        logs_branches = []
        for branch in branches:
            logs_branch = spool_jaxpr(branch.jaxpr, argnames, tags)
            logs_branches.append(logs_branch)
        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)),
            logs_branches[0],
        )
        eqn.outvars.extend(jax.tree.leaves(logs_eqn))
        return logs_eqn

    def spool_while_p(eqn: JaxprEqn) -> logdict:
        logs_cond = spool_jaxpr(eqn.params["cond_jaxpr"].jaxpr, argnames, tags)
        logs_body = spool_jaxpr(eqn.params["body_jaxpr"].jaxpr, argnames, tags)
        if logs_cond or logs_body:
            print(
                "Warning: Spooling for while loops is not supported due to non-static length."
            )
        return logdict({})

    def spool_jit_p(eqn: JaxprEqn) -> logdict:
        logs_jaxpr = spool_jaxpr(eqn.params["jaxpr"].jaxpr, argnames, tags)
        if logs_jaxpr:
            logs_eqn = jax.tree.map(
                lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_jaxpr
            )
            eqn.outvars.extend(jax.tree.leaves(logs_eqn))
            eqn.primitive = jax.extend.core.primitives.call_p
            eqn.params = {"call_jaxpr": eqn.params["jaxpr"].jaxpr}
            return logs_eqn
        else:
            return logdict({})

    def spool_call_p(eqn: JaxprEqn) -> logdict:
        logs_call_jaxpr = spool_jaxpr(eqn.params["call_jaxpr"], argnames, tags)
        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_call_jaxpr
        )
        eqn.outvars.extend(jax.tree_util.tree_leaves(logs_eqn))
        return logs_eqn

    def spool_remat_p(eqn: JaxprEqn) -> logdict:
        logs_remat_jaxpr = spool_jaxpr(eqn.params["jaxpr"], argnames, tags)
        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)),
            logs_remat_jaxpr,
        )
        eqn.outvars.extend(jax.tree_util.tree_leaves(logs_eqn))
        return logs_eqn

    logs_eqns = []
    for i in range(len(jaxpr.eqns)):
        eqn = jaxpr.eqns[i]
        logs_eqn = None
        if eqn.primitive == lox_p:
            logs_eqn = spool_lox_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.scan_p:
            logs_eqn = spool_scan_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.cond_p:
            logs_eqn = spool_cond_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.while_p:
            logs_eqn = spool_while_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.jit_p:
            logs_eqn = spool_jit_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.call_p:
            logs_eqn = spool_call_p(eqn)
        elif eqn.primitive == jax._src.ad_checkpoint.remat_p:
            logs_eqn = spool_remat_p(eqn)

        if logs_eqn:
            logs_eqns.append(logs_eqn)

    if logs_eqns:

        def combine(logs_eqns):
            """Combines the logs from multiple equations into a single logdict."""
            logs_jaxpr = logs_eqns[0]
            for logs_eqn in logs_eqns[1:]:
                logs_jaxpr += logs_eqn
            return logs_jaxpr

        logs_jaxpr = apply(combine, jaxpr, logs_eqns)
        jaxpr.outvars.extend(jax.tree_util.tree_leaves(logs_jaxpr))
    else:
        logs_jaxpr = logdict({})

    return logs_jaxpr
