from functools import wraps
from typing import Any, Callable, Hashable, Iterable

import jax
import jax._src.ad_checkpoint
import jax.core
import jax.extend
import jax.numpy as jnp
from jax import ShapeDtypeStruct
from jax._src import source_info_util
from jax.core import ShapedArray
from jax.extend.core import ClosedJaxpr, Jaxpr, JaxprEqn, Literal, Var

from lox.logdict import logdict, stepdict
from lox.primitive import lox_p
from lox.stripping import strip_jaxpr
from lox.utils import flatten, is_hashable

AxisName = Hashable


def _fill_value_for_dtype(dtype):
    if jnp.issubdtype(dtype, jnp.floating):
        return float("nan")
    elif jnp.issubdtype(dtype, jnp.integer):
        return 0
    else:
        return False


def _make_fill_eqn(aval: ShapedArray, ctx) -> tuple[JaxprEqn, Var]:
    """Creates a call_p equation that produces a fill constant with the given aval."""
    fill = _fill_value_for_dtype(aval.dtype)
    fill_closed = jax.make_jaxpr(lambda: jnp.full(aval.shape, fill, aval.dtype))()
    fill_jaxpr = fill_closed.jaxpr
    const_literals = [Literal(c, jax.core.get_aval(c)) for c in fill_closed.consts]
    call_jaxpr = fill_jaxpr.replace(
        constvars=[],
        invars=[*fill_jaxpr.constvars, *fill_jaxpr.invars],
    )
    out_var = Var(aval=aval)
    eqn = JaxprEqn(
        const_literals,
        [out_var],
        jax.extend.core.primitives.call_p,
        {"call_jaxpr": call_jaxpr},
        (),
        source_info_util.current(),
        ctx,
    )
    return eqn, out_var


def spool(
    fun: Callable,
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
    interval: int | None = None,
    reduce: str | None = None,
    prefix: str = "",
    unify: bool = False,
) -> Callable:
    """
    Spools a function to extract logs generated during its execution.
    Logs are generated by every call to ``lox.log`` within the function.
    Note that spooling also has to obey the underlying laws of JAX.
    Hence all shapes and lengths of the logs must be inferrable during compile time.
    As a direct consequence, loops with non-static lengths (e.g. while loops) are not supported.
    Another implication of this is that spooling an already jitted function that contains
    logging operations will trigger recompilation.

    Args:
        fun (Callable): The function to be spooled.
        argnames (Iterable[str] | None): An optional list of argument names to be spooled.
        tags (Iterable[str] | None): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
        interval (int | None): An optional interval to subsample the logs.
        reduce (str | None): An optional reduction method to apply to the logs.
        prefix (str): An optional prefix to add to the log keys.
        unify (bool): When True, cond branches with different log keys are unified by
            filling missing keys with NaN (float), 0 (int), or False (bool). When False
            (default), divergent branch log keys raise a ValueError.

    Returns:
        Callable: A wrapped function that returns the spooled jaxpr and logs.

    Example:
        Here is an example of how to use ``spool`` to extract logs from a function.

        >>> def f(x):
        >>>     lox.log({"x": x})
        >>>     return x + 1.0
        >>> spool(f)(1.0)
        (2.0, {'x': 1.0})

        Spooling works with arbitrarily nested functions and higher order primitives such as
        ``jax.lax.scan`` or ``jax.lax.cond``.
        The following example shows how to use spooling with a scan operation over the
        previously defined function ``f``.

        >>> def g(xs):
        >>>     carry, ys = jax.lax.scan(lambda c, x: (f(c), x), xs)
        >>>     lox.log({"carry": carry})
        >>> return ys
        >>> spool(g)(jnp.arange(3))
        (Array([2., 3., 4.]), {'carry': 3., 'x': Array([0., 1., 2.])})

        When logging inside of ``jax.lax.cond`` all branches must have the same log structure.
        In this case, both branches return a logdict containing only the key :string:`x`.

        >>> def h(x):
        >>>     return jax.lax.cond(x > 0, lambda x: f(x), lambda x: f(x + 1), x)
        >>> x = 3.0
        >>> spool(h)(x)
        (4.0, {'x': 3.0})

        The optional argument `keep_logs` can be set to `True` to keep the logs in the jaxpr.
        By default, spooling a function twice

        >>> def j(x):
        >>>     y, logs = spool(f)(x)
        >>>     return y
        >>> spool(j)(1.0)
        2.0

    """

    @wraps(fun)
    def wrapped(*args, **kwargs):
        args_flat, structure = jax.tree.flatten((args, kwargs))
        static_argnums = tuple(i for i, arg in enumerate(args_flat) if is_hashable(arg))
        closed_jaxpr, out_spooled_shape = make_spooled_jaxpr(
            flatten(fun, structure),
            static_argnums=static_argnums,
            argnames=argnames,
            tags=tags,
            keep_logs=keep_logs,
            unify=unify,
        )(*args_flat)
        dynamic_args_flat = tuple(arg for arg in args_flat if not is_hashable(arg))
        out_spooled_structure = jax.tree.structure(out_spooled_shape)
        out_spooled_flat = jax.core.eval_jaxpr(
            closed_jaxpr.jaxpr, closed_jaxpr.literals, *dynamic_args_flat
        )
        out, logs = jax.tree_util.tree_unflatten(
            out_spooled_structure, out_spooled_flat
        )
        if interval is not None:
            logs = logs.slice[::interval]
        if reduce is not None:
            logs = logs.reduce(reduce)
        if prefix:
            logs = logs.prefix(prefix)
        return out, logs

    return wrapped


def make_spooled_jaxpr(
    fun: Callable,
    static_argnums: int | Iterable[int] = (),
    argnames: Iterable[str] | None = None,
    tags: Iterable[str] | None = None,
    keep_logs: bool = False,
    unify: bool = False,
) -> Callable[..., tuple[ClosedJaxpr, Any]]:
    """
    Creates a spooled jaxpr for the given function, extracting logs and their shapes.

    Args:
        fun (Callable): The function to create a jaxpr for.
        static_argnums (int | Iterable[int]): The indices of static arguments.
        argnames (Optional[Iterable[str]]): An optional list of argument names to be spooled.
        tags (Optional[Iterable[str]]): An optional list of tags to filter the logs.
        keep_logs (bool): Whether to keep logs in the jaxpr.
        unify (bool): Whether to unify divergent cond branch log keys with fills.
    Returns:
        Callable[..., ClosedJaxpr | tuple[ClosedJaxpr, Any]]: A wrapped function that returns the jaxpr and logs.
    """

    def make_jaxpr_f(*args, **kwargs):
        closed_jaxpr, out_shape = jax.make_jaxpr(
            fun,
            static_argnums=static_argnums,
            return_shape=True,
        )(*args, **kwargs)
        new_jaxpr, logs = spool_jaxpr(
            closed_jaxpr.jaxpr, argnames=argnames, tags=tags, unify=unify
        )
        closed_jaxpr = ClosedJaxpr(new_jaxpr, closed_jaxpr.consts)
        logs_shape = jax.tree_util.tree_map(
            lambda v: ShapeDtypeStruct(v.aval.shape, v.aval.dtype), logs
        )
        if not keep_logs:
            stripped = strip_jaxpr(closed_jaxpr.jaxpr, argnames=argnames, tags=tags)
            closed_jaxpr = ClosedJaxpr(stripped, closed_jaxpr.consts)
        return closed_jaxpr, (out_shape, logs_shape)

    make_jaxpr_f.__module__ = "jax"
    if hasattr(fun, "__qualname__"):
        make_jaxpr_f.__qualname__ = f"make_jaxpr({fun.__qualname__})"
    if hasattr(fun, "__name__"):
        make_jaxpr_f.__name__ = f"make_jaxpr({fun.__name__})"
    return make_jaxpr_f


def apply(f: Callable, ctx, *invars: Any) -> tuple[JaxprEqn, Any]:
    """
    Creates a call_p equation that applies f to invars.

    Args:
        f (Callable): The function to apply.
        ctx: The JaxprEqnContext for the new equation.
        *invars: The input variables to the function.
    Returns:
        tuple[JaxprEqn, Any]: The new equation and the output variables.
    """
    invars_avals = jax.tree.map(lambda invar: invar.aval, invars)
    closed_jaxpr_f, shape_f = jax.make_jaxpr(f, return_shape=True)(*invars_avals)
    structure_f = jax.tree.structure(shape_f)
    jaxpr_f = closed_jaxpr_f.jaxpr
    const_literals = [Literal(c, jax.core.get_aval(c)) for c in closed_jaxpr_f.consts]
    call_jaxpr = jaxpr_f.replace(
        constvars=[],
        invars=[*jaxpr_f.constvars, *jaxpr_f.invars],
    )
    eqn_f = JaxprEqn(
        [*const_literals, *jax.tree.leaves(invars)],
        call_jaxpr.outvars,
        jax.extend.core.primitives.call_p,
        {"call_jaxpr": call_jaxpr},
        (),
        source_info_util.current(),
        ctx,
    )
    outvars = jax.tree.unflatten(structure_f, call_jaxpr.outvars)
    return eqn_f, outvars


def spool_jaxpr(
    jaxpr: Jaxpr,
    argnames: Iterable[str] | None,
    tags: Iterable[str] | None,
    unify: bool = False,
) -> tuple[Jaxpr, logdict]:
    """
    Spools the logs from a jaxpr, extracting logs and their shapes from each equation.
    Returns a new Jaxpr with log outputs appended (does not mutate the input).

    Args:
        jaxpr (Jaxpr): The jaxpr to spool.
        argnames (Iterable[str] | None): An optional list of argument names to be spooled.
        tags (Iterable[str] | None): An optional list of tags to filter the logs.
        unify (bool): Whether to unify divergent cond branch log keys with fills.
    Returns:
        tuple[Jaxpr, logdict]: The new jaxpr with log outputs and the logs.
    """
    ctx = jaxpr.eqns[0].ctx if jaxpr.eqns else None

    def spool_lox_p(eqn: JaxprEqn) -> logdict:
        logs_eqn = jax.tree.unflatten(eqn.params["structure"], eqn.invars)
        if argnames:
            if tags is None or not any(tag in tags for tag in eqn.params["tags"]):
                logs_eqn = logs_eqn.filter(lambda k, _: k in argnames)
        elif tags:
            if not any(tag in tags for tag in eqn.params["tags"]):
                logs_eqn = logdict({})
        return logs_eqn

    def spool_scan_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        inner_closed = eqn.params["jaxpr"]
        new_inner_jaxpr, logs_jaxpr = spool_jaxpr(inner_closed.jaxpr, argnames, tags, unify)

        if not logs_jaxpr:
            return eqn, logdict({}), []

        logs_jaxpr_avals = jax.tree_util.tree_map(lambda l: l.aval, logs_jaxpr)
        logs_scan_avals = jax.tree_util.tree_map(
            lambda aval: ShapedArray((eqn.params["length"],) + aval.shape, aval.dtype),
            logs_jaxpr_avals,
        )
        logs_scan = jax.tree.map(lambda aval: Var(aval=aval), logs_scan_avals)

        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree.leaves(logs_scan)],
            params={**eqn.params, "jaxpr": ClosedJaxpr(new_inner_jaxpr, inner_closed.consts)},
        )

        def unstack(logs_scan):
            return jax.tree.map(
                lambda l: l.reshape((-1,) + l.shape[2:]),
                logs_scan,
            )

        unstack_eqn, logs_eqn = apply(unstack, ctx, logs_scan)
        return new_eqn, logs_eqn, [unstack_eqn]

    def spool_cond_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        branches = eqn.params["branches"]
        new_branches_data = []
        for branch in branches:
            new_branch_jaxpr, logs_branch = spool_jaxpr(branch.jaxpr, argnames, tags, unify)
            new_branches_data.append((new_branch_jaxpr, branch.consts, logs_branch))

        if not any(logs for _, _, logs in new_branches_data):
            return eqn, logdict({}), []

        # Collect all data keys and validate shape/dtype consistency
        all_data_keys = sorted(
            set(k for _, _, logs in new_branches_data for k in logs.keys())
        )
        data_key_avals: dict[str, ShapedArray] = {}
        for key in all_data_keys:
            for _, _, logs in new_branches_data:
                if key in logs:
                    aval = logs[key].aval
                    if key in data_key_avals:
                        existing = data_key_avals[key]
                        if (existing.shape, existing.dtype) != (aval.shape, aval.dtype):
                            raise ValueError(
                                f"lox.spool: log key '{key}' has mismatched shape/dtype "
                                f"across cond branches: {existing} vs {aval}"
                            )
                    else:
                        data_key_avals[key] = aval

        # Check for divergent data key sets
        all_data_keys_set = set(all_data_keys)
        branch_data_key_sets = [set(logs.keys()) for _, _, logs in new_branches_data]
        has_divergent_data = any(ks != all_data_keys_set for ks in branch_data_key_sets)

        if has_divergent_data and not unify:
            parts = [
                f"branch {i} missing {sorted(all_data_keys_set - ks)}"
                for i, ks in enumerate(branch_data_key_sets)
                if ks != all_data_keys_set
            ]
            raise ValueError(
                f"lox.spool: cond branches log different keys ({'; '.join(parts)}). "
                f"Use spool(..., unify=True) to fill missing keys with NaN/zero."
            )

        # Collect all step dimension names and their key avals
        all_step_dims = sorted(
            set(dim for _, _, logs in new_branches_data for dim in logs.steps.keys())
        )
        step_dim_key_avals: dict[str, dict[str, ShapedArray]] = {}
        for dim in all_step_dims:
            step_dim_key_avals[dim] = {}
            for _, _, logs in new_branches_data:
                if dim in logs.steps:
                    for k, v in logs.steps[dim].items():
                        aval = v.aval
                        if k in step_dim_key_avals[dim]:
                            existing = step_dim_key_avals[dim][k]
                            if (existing.shape, existing.dtype) != (aval.shape, aval.dtype):
                                raise ValueError(
                                    f"lox.spool: step '{dim}.{k}' has mismatched "
                                    f"shape/dtype across cond branches: {existing} vs {aval}"
                                )
                        else:
                            step_dim_key_avals[dim][k] = aval

        # Check for divergent step structures
        if not unify:
            for dim in all_step_dims:
                all_step_keys = set(step_dim_key_avals[dim].keys())
                for _, _, logs in new_branches_data:
                    branch_step_keys = set(logs.steps[dim].keys()) if dim in logs.steps else set()
                    if branch_step_keys != all_step_keys:
                        raise ValueError(
                            f"lox.spool: cond branches have different step keys for "
                            f"dimension '{dim}'. Use spool(..., unify=True) to fill "
                            f"missing step entries with 0."
                        )

        # Build unified branch jaxprs
        n_orig_outvars = [len(branch.jaxpr.outvars) for branch in branches]
        final_branches = []

        for i, (new_branch_jaxpr, branch_consts, logs_branch) in enumerate(new_branches_data):
            n_orig = n_orig_outvars[i]
            original_outvars = new_branch_jaxpr.outvars[:n_orig]
            extra_eqns = []

            # Fill missing data keys
            for key in all_data_keys:
                if key not in logs_branch:
                    fill_eqn, fill_var = _make_fill_eqn(data_key_avals[key], ctx)
                    extra_eqns.append(fill_eqn)
                    logs_branch[key] = fill_var

            # Fill missing step entries
            for dim in all_step_dims:
                if dim not in logs_branch.steps:
                    logs_branch.steps[dim] = stepdict({})
                for step_key in sorted(step_dim_key_avals[dim].keys()):
                    if step_key not in logs_branch.steps[dim]:
                        step_aval = step_dim_key_avals[dim][step_key]
                        fill_eqn, fill_var = _make_fill_eqn(step_aval, ctx)
                        extra_eqns.append(fill_eqn)
                        logs_branch.steps[dim][step_key] = fill_var

            # Construct unified logdict with sorted keys for deterministic leaf ordering
            unified_data = {k: logs_branch[k] for k in all_data_keys}
            unified_steps = {
                dim: stepdict(
                    {k: logs_branch.steps[dim][k] for k in sorted(step_dim_key_avals[dim].keys())}
                )
                for dim in all_step_dims
            }
            unified_logs = logdict(unified_data, **unified_steps)
            unified_log_leaves = jax.tree.leaves(unified_logs)

            final_branch_jaxpr = new_branch_jaxpr.replace(
                eqns=list(new_branch_jaxpr.eqns) + extra_eqns,
                outvars=[*original_outvars, *unified_log_leaves],
            )
            final_branches.append(ClosedJaxpr(final_branch_jaxpr, branch_consts))

        # Fresh outer Vars for the log outputs, same unified structure
        unified_data_eqn = {k: Var(aval=data_key_avals[k]) for k in all_data_keys}
        unified_steps_eqn = {
            dim: stepdict(
                {k: Var(aval=step_dim_key_avals[dim][k]) for k in sorted(step_dim_key_avals[dim].keys())}
            )
            for dim in all_step_dims
        }
        logs_eqn = logdict(unified_data_eqn, **unified_steps_eqn)

        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree.leaves(logs_eqn)],
            params={**eqn.params, "branches": tuple(final_branches)},
        )
        return new_eqn, logs_eqn, []

    def spool_while_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        _, logs_cond = spool_jaxpr(eqn.params["cond_jaxpr"].jaxpr, argnames, tags, unify)
        _, logs_body = spool_jaxpr(eqn.params["body_jaxpr"].jaxpr, argnames, tags, unify)
        if logs_cond or logs_body:
            print(
                "Warning: Spooling for while loops is not supported due to non-static length."
            )
        return eqn, logdict({}), []

    def spool_jit_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        inner_closed = eqn.params["jaxpr"]
        new_inner_jaxpr, logs_jaxpr = spool_jaxpr(inner_closed.jaxpr, argnames, tags, unify)
        if logs_jaxpr:
            logs_eqn = jax.tree.map(
                lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_jaxpr
            )
            const_literals = [Literal(c, jax.core.get_aval(c)) for c in inner_closed.consts]
            call_jaxpr = new_inner_jaxpr.replace(
                constvars=[],
                invars=[*new_inner_jaxpr.constvars, *new_inner_jaxpr.invars],
            )
            new_eqn = eqn.replace(
                primitive=jax.extend.core.primitives.call_p,
                invars=[*const_literals, *eqn.invars],
                outvars=[*eqn.outvars, *jax.tree.leaves(logs_eqn)],
                params={"call_jaxpr": call_jaxpr},
            )
            return new_eqn, logs_eqn, []
        else:
            return eqn, logdict({}), []

    def spool_call_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        new_call_jaxpr, logs_call_jaxpr = spool_jaxpr(
            eqn.params["call_jaxpr"], argnames, tags, unify
        )
        if not logs_call_jaxpr:
            return eqn, logdict({}), []

        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)), logs_call_jaxpr
        )
        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree_util.tree_leaves(logs_eqn)],
            params={**eqn.params, "call_jaxpr": new_call_jaxpr},
        )
        return new_eqn, logs_eqn, []

    def spool_remat_p(eqn: JaxprEqn) -> tuple[JaxprEqn, logdict, list[JaxprEqn]]:
        new_remat_jaxpr, logs_remat_jaxpr = spool_jaxpr(
            eqn.params["jaxpr"], argnames, tags, unify
        )
        if not logs_remat_jaxpr:
            return eqn, logdict({}), []

        logs_eqn = jax.tree.map(
            lambda l: Var(aval=ShapedArray(l.aval.shape, l.aval.dtype)),
            logs_remat_jaxpr,
        )
        new_eqn = eqn.replace(
            outvars=[*eqn.outvars, *jax.tree_util.tree_leaves(logs_eqn)],
            params={**eqn.params, "jaxpr": new_remat_jaxpr},
        )
        return new_eqn, logs_eqn, []

    new_eqns = []
    extra_eqns = []
    logs_eqns = []

    for eqn in jaxpr.eqns:
        new_eqn = eqn
        logs_eqn = None
        extra = []

        if eqn.primitive == lox_p:
            logs_eqn = spool_lox_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.scan_p:
            new_eqn, logs_eqn, extra = spool_scan_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.cond_p:
            new_eqn, logs_eqn, extra = spool_cond_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.while_p:
            new_eqn, logs_eqn, extra = spool_while_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.jit_p:
            new_eqn, logs_eqn, extra = spool_jit_p(eqn)
        elif eqn.primitive == jax.extend.core.primitives.call_p:
            new_eqn, logs_eqn, extra = spool_call_p(eqn)
        elif eqn.primitive == jax._src.ad_checkpoint.remat_p:
            new_eqn, logs_eqn, extra = spool_remat_p(eqn)

        new_eqns.append(new_eqn)
        extra_eqns.extend(extra)
        if logs_eqn:
            logs_eqns.append(logs_eqn)

    new_outvars = list(jaxpr.outvars)
    if logs_eqns:

        def combine(logs_eqns):
            """Combines the logs from multiple equations into a single logdict."""
            logs_jaxpr = logs_eqns[0]
            for logs_eqn in logs_eqns[1:]:
                logs_jaxpr += logs_eqn
            return logs_jaxpr

        combine_eqn, logs_jaxpr = apply(combine, ctx, logs_eqns)
        extra_eqns.append(combine_eqn)
        new_outvars.extend(jax.tree_util.tree_leaves(logs_jaxpr))
    else:
        logs_jaxpr = logdict({})

    new_jaxpr = jaxpr.replace(outvars=new_outvars, eqns=new_eqns + extra_eqns)
    return new_jaxpr, logs_jaxpr
